" vim: set ft=vim

" Keys
let mapleader = ","

" Appearance
syntax on
set t_Co=256
set cursorline
set nowrap
set number

" Show all tab chars and trailing whitespace
set listchars=tab:>.,trail:.,extends:#,nbsp:.
set list

colorscheme dracula


" Text
set shiftwidth=4
set tabstop=4
set softtabstop=4
set smarttab
set expandtab
set autoindent
set backspace=2


" File configurations
filetype on
filetype indent on
filetype plugin on
set noswapfile

" Search
set incsearch
set ignorecase
set smartcase
set hlsearch

" Key mappings
map tk :tabnext<CR>
map tj :tabprev<CR>

" Remove trailing whitespace
map <leader>e :%s/\s\+$//<CR>:let @/=''<CR>

