" vim: set ft=vim

" Keys
let mapleader = ","

" Appearance
syntax on
set t_Co=256
set cursorline
set nowrap
set number
set laststatus=2
set ruler

" Show all tab chars and trailing whitespace
set listchars=tab:>.,trail:.,extends:#,nbsp:.
set list

packadd! dracula
syntax enable
colorscheme dracula


" Text
set shiftwidth=4
set tabstop=4
set softtabstop=4
set smarttab
set expandtab
set autoindent
set backspace=2
"set clipboard+=unnamed


" File configurations
filetype on
filetype indent on
filetype plugin on
set noswapfile

" Search
set incsearch
set ignorecase
set smartcase
set hlsearch
" clear highlighted search using the space bar
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

" Key mappings
map tk :tabnext<CR>
map tj :tabprev<CR>

" Remove trailing whitespace
map <leader>e :%s/\s\+$//<CR>:let @/=''<CR>

" Plugin configurations
let g:vim_markdown_folding_disabled = 1

" For ctrlp
set wildignore+=*.o,*.obj,.git,*.pyc.
" Linux / Mac
set wildignore+=*/.git/*,*/node_modules/*
" Windows
set wildignore+=.git\*,Build\*,.sass-cache\*,node_modules\*

" Insert date
iab <expr> dts strftime("%Y-%m-%d")

" Autocmd
autocmd BufEnter * if expand("%:p:h") !~ '^/tmp' | silent! lcd %:p:h | endif

