" vim: set ft=vim

" Keys
let mapleader = ","

" Appearance
syntax on
set t_Co=256
set cursorline
set nowrap
set number

colorscheme wombat256mod

" File configurations
filetype on
filetype indent on
filetype plugin on
set noswapfile

" Search
set incsearch
set ignorecase
set smartcase
set hlsearch

" Key mappings
map tk :tabnext<CR>
map tj :tabprev<CR>

