version: 2
updates:
  # Enable version updates for vim packages
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "smerrell"
    open-pull-requests-limit: 10
